export type RecordCategory = "book" | "movie" | "game" | "other"

export type RecordEntry = {
  date?: string | Date
  title: string
  category?: RecordCategory
  url?: string
  creator?: string
  releaseDate?: string
  country?: string | string[]
  notes?: string
  favorite?: true
}

export type ResolvedRecordEntry = {
  date?: Date
  title: string
  category: RecordCategory
  url: string
  creator: string
  releaseDate: string
  country: string[]
  notes: string
  favorite: boolean
}

const recordEntries: RecordEntry[] = [

{
  date: "2026/05/27",
  title: "グランド・イリュージョン／ダイヤモンド・ミッション",
  category: "movie",
  releaseDate: "2025",
  country: ["US"],
},
{
  date: "2026/03/26",
  title: "ストレイト・ストーリー",
  category: "movie",
  releaseDate: "1999",
  country: ["US"],
  notes: "急にアメリカの田舎のデカすぎる畑が見たくなって見た　いい映画",
},
{
  date: "2026/03/26",
  title: "Bag Boy Lover Boy",
  category: "movie",
  releaseDate: "2014",
  country: ["US"],
},
{
  date: "2025/09/27",
  title: "犯罪都市 PUNISHMENT",
  category: "movie",
  releaseDate: "2024",
  country: ["KR"],
  notes: "安定のマドンソク、セクシーなキムムヨル",
},
{
  date: "2025/09/19",
  title: "8mm",
  category: "movie",
  releaseDate: "1999",
  country: ["US"],
  notes: "ニコラスケイジの相棒・一瞬しか出てこない囚人の二人がやたら爆イケで、見終わった後にキャスト調べたらホアキンフェニックスとノーマンリーダスでそりゃそうすぎた"
},
{
  date: "2025/08/06",
  title: "トワイライト・ウォリアーズ 決戦！九龍城砦",
  category: "movie",
  releaseDate: "2024",
  country: ["HK"],
  favorite: true,
},
{
  date: "2025/07/30",
  title: "美しき仕事 4Kレストア版",
  category: "movie",
  releaseDate: "1999",
  country: ["FR"],
},
{
  date: "2025/07/30",
  title: "召使",
  category: "movie",
  releaseDate: "1963",
  country: ["GB"],
  notes: "萌え❣️",
  favorite: true,
},
{
  date: "2025/07/30",
  title: "テオレマ",
  category: "movie",
  releaseDate: "1968",
  country: ["IT"],
},
{
  date: "2025/07/03",
  title: "ブロークバック・マウンテン",
  category: "movie",
  releaseDate: "2005",
  country: ["US"],
},
{
  date: "2025/05/31",
  title: "教皇選挙",
  category: "movie",
  releaseDate: "2024",
  country: ["GB", "US"],
  notes: "話全然違うのに空気がSaltburnすぎるだろと思ったら美術監督同じだった",
},
{
  date: "2024/11/10",
  title: "孤狼の血 LEVEL2",
  category: "movie",
  releaseDate: "2021",
  country: ["JP"],
},
{
  date: "2024/11/10",
  title: "ストレンジ・ウェイ・オブ・ライフ",
  category: "movie",
  releaseDate: "2023",
  country: ["ES", "FR"],
},
{
  date: "2024/08/27",
  title: "翔んで埼玉",
  category: "movie",
  releaseDate: "2018",
  country: ["JP"],
},
{
  date: "2024/08/10",
  title: "犯罪都市 NO WAY OUT",
  category: "movie",
  releaseDate: "2023",
  country: ["KR"],
  notes: "安定のマドンソク、セクシーなイ・ジュニョク",
},
{
  date: "2024/08/02",
  title: "ブエナ・ビスタ・ソシアル・クラブ",
  category: "movie",
  releaseDate: "1999",
  country: ["DE", "US", "FR", "CU"],
},
{
  date: "2024/07/28",
  title: "アンダーグラウンド",
  category: "movie",
  releaseDate: "1995",
  country: ["FR", "DE", "HU"],
  notes: "すごい映画　ラスト30分が体感2時間",
  favorite: true,
},
{
  date: "2024/07/28",
  title: "殺人鬼の存在証明",
  category: "movie",
  releaseDate: "2021",
  country: ["RU"],
  notes: "時系列の入れ替え方がゲームぽい",
},
{
  date: "2024/06/22",
  title: "遊星からの物体X",
  category: "movie",
  releaseDate: "1982",
  country: ["US"],
  notes: "縄を切ってくれマクレディ！！！！！（ガン無視）",
},
{
  date: "2024/03/07",
  title: "犬人間",
  category: "movie",
  releaseDate: "2022",
  country: ["NO"],
  notes: "お仕置きが思ったより優しめで変な笑い出た",
},
{
  date: "2024/02/14",
  title: "ゴールデンカムイ",
  category: "movie",
  releaseDate: "2024",
  country: ["JP"],
  notes: "白石由竹は本当に存在していて、本当にヌルヌルしている",
},
{
  date: "2024/01/18",
  title: "首",
  category: "movie",
  releaseDate: "2023",
  country: ["JP"],
  notes: "今年の漢字一文字は首",
  favorite: true,
},
{
  date: "2024/01/03",
  title: "犯罪都市 THE ROUNDUP",
  category: "movie",
  releaseDate: "2022",
  country: ["KR"],
  notes: "安定のマドンソク、セクシーなカンヘサン",
},
{
  date: "2024/01/01",
  title: "Saltburn",
  category: "movie",
  releaseDate: "2023",
  country: ["GB", "US"],
  notes: "無敵のバリーコーガンと快楽の園",
},
{
  date: "2024/01/01",
  title: "楽園の夜",
  category: "movie",
  releaseDate: "2019",
  country: ["KR"],
},
{
  date: "2023/12/20",
  title: "⻤太郎誕生 ゲゲゲの謎",
  category: "movie",
  releaseDate: "2023",
  country: ["JP"],
},
{
  date: "2023/11/07",
  title: "孤狼の血",
  category: "movie",
  releaseDate: "2018",
  country: ["JP"],
},
{
  date: "2023/08/23",
  title: "ミンナのウタ",
  category: "movie",
  releaseDate: "2023",
  country: ["JP"],
},
{
  date: "2023/07/04",
  title: "名もなき野良犬の輪舞",
  category: "movie",
  releaseDate: "2016",
  country: ["KR"],
},
{
  date: "2023/06/23",
  title: "SP 革命篇",
  category: "movie",
  releaseDate: "2011",
  country: ["JP"],
  notes: "尾形の部屋かなりダイゴの部屋でよかった",
},
{
  date: "2023/06/23",
  title: "SP 野望篇",
  category: "movie",
  releaseDate: "2010",
  country: ["JP"],
},
{
  date: "2023/04/13",
  title: "THE FIRST SLAM DUNK",
  category: "movie",
  releaseDate: "2022",
  country: ["JP"],
},
{
  date: "2022/11/16",
  title: "貞子DX",
  category: "movie",
  releaseDate: "2022",
  country: ["JP"],
  notes: "なんか色々と令和でよかった",
},
{
  date: "2022/10/20",
  title: "天使の涙 4Kレストア版",
  category: "movie",
  releaseDate: "1995",
  country: ["HK"],
},
{
  date: "2022/10/19",
  title: "ブエノスアイレス 4Kレストア版",
  category: "movie",
  releaseDate: "1997",
  country: ["HK"],
},
{
  date: "2022/10/16",
  title: "クローズZERO II",
  category: "movie",
  releaseDate: "2009",
  country: ["JP"],
},
{
  date: "2022/10/16",
  title: "クローズZERO",
  category: "movie",
  releaseDate: "2007",
  country: ["JP"],
},
{
  date: "2022/10/02",
  title: "犯罪都市",
  category: "movie",
  releaseDate: "2017",
  country: ["KR"],
  notes: "安定のマドンソク、セクシーなユンゲサン",
},
{
  date: "2022/10/02",
  title: "パルプ・フィクション",
  category: "movie",
  releaseDate: "1994",
  country: ["US"],
},
{
  date: "2022/10/02",
  title: "レニングラード・カウボーイズ・ゴー・アメリカ",
  category: "movie",
  releaseDate: "1989",
  country: ["FI", "SE"],
  notes: "ジャームッシュが出てる",
},
{
  date: "2022/09/17",
  title: "スカーフェイス",
  category: "movie",
  releaseDate: "1983",
  country: ["US"],
},
{
  date: "2022/09/17",
  title: "HiGH&LOW THE WORST X",
  category: "movie",
  releaseDate: "2022",
  country: ["JP"],
  notes: "見すぎて天下井のセリフ完コピした",
  favorite: true,
},
{
  date: "2022/08/28",
  title: "HiGH&LOW THE WORST",
  category: "movie",
  releaseDate: "2019",
  country: ["JP"],
},
{
  date: "2022/07/15",
  title: "コーヒー&シガレッツ",
  category: "movie",
  releaseDate: "2003",
  country: ["US"],
  notes: "GZAとRZAとビルマーレイの話好き",
},
{
  date: "2022/07/15",
  title: "呪詛",
  category: "movie",
  releaseDate: "2022",
  country: ["TW"],
},
{
  date: "2022/05/15",
  title: "フューリーズ 復讐の女神",
  category: "movie",
  releaseDate: "2019",
  country: ["AU"],
  notes: "なんか妙にいいシーンがある",
},
{
  date: "2022/05/15",
  title: "フレンチ・ディスパッチ　ザ・リバティ、カンザス・イヴニング・サン別冊",
  category: "movie",
  releaseDate: "2021",
  country: ["US"],
},
{
  date: "2022/05/11",
  title: "ゲーム・オブ・デス",
  category: "movie",
  releaseDate: "2017",
  country: ["CA", "FR", "US"],
  notes: "なんか妙にいいシーンがある",
},
{
  date: "2022/02/11",
  title: "ハウス・オブ・グッチ",
  category: "movie",
  releaseDate: "2021",
  country: ["US"],
},
{
  date: "2022/01/11",
  title: "ノーカントリー",
  category: "movie",
  releaseDate: "2007",
  country: ["US"],
  notes: "アントンシガー",
},
{
  date: "2022/01/09",
  title: "人斬り",
  category: "movie",
  releaseDate: "1969",
  country: ["JP"],
  notes: "武市が怖すぎる",
},
{
  date: "2021/11/25",
  title: "悪人伝",
  category: "movie",
  releaseDate: "2018",
  country: ["KR"],
},
{
  date: "2021/11/23",
  title: "ブリーダー",
  category: "movie",
  releaseDate: "1999",
  country: ["DK"],
  notes: "マッツミケルセンの自室が爆イケ",
},
{
  date: "2021/11/20",
  title: "シングルマン",
  category: "movie",
  releaseDate: "2009",
  country: ["US"],
},
{
  date: "2021/10/26",
  title: "ギャングバスターズ",
  category: "movie",
  releaseDate: "2012",
  country: ["US"],
  notes: "意外といい話でよかった",
},
{
  date: "2021/08/14",
  title: "パーマネント・バケーション",
  category: "movie",
  releaseDate: "1980",
  country: ["US"],
},
{
  date: "2021/08/07",
  title: "ゴースト・ドッグ",
  category: "movie",
  releaseDate: "1999",
  country: ["FR", "DE", "US", "JP"],
  notes: "大好き",
  favorite: true,
},
{
  date: "2021/08/06",
  title: "ホーボー・ウィズ・ショットガン",
  category: "movie",
  releaseDate: "2011",
  country: ["CA"],
  notes: "Ride Shotgun!",
},
{
  date: "2021/08/03",
  title: "ザ・レイド GOKUDO",
  category: "movie",
  releaseDate: "2013",
  country: ["ID", "US"],
  notes: "最高の映画",
  favorite: true,
},
{
  date: "2021/07/24",
  title: "ザ・レイド",
  category: "movie",
  releaseDate: "2011",
  country: ["ID", "US"],
},
{
  date: "2021/07/20",
  title: "ルクス・エテルナ 永遠の光",
  category: "movie",
  releaseDate: "2019",
  country: ["FR"],
},
{
  date: "2021/07/17",
  title: "Mr.ノーバディ",
  category: "movie",
  releaseDate: "2021",
  country: ["US"],
},
{
  date: "2021/07/11",
  title: "ジョン・ウィック",
  category: "movie",
  releaseDate: "2014",
  country: ["US"],
},
{
  date: "2021/07/10",
  title: "CLIMAX クライマックス",
  category: "movie",
  releaseDate: "2018",
  country: ["FR", "BE"],
},
{
  date: "2021/07/09",
  title: "ジョーカー",
  category: "movie",
  releaseDate: "2019",
  country: ["US"],
  notes: "I used to think that my life was a tragedy, but now I realize, it's a fucking comedy.",
},
{
  date: "2021/07/08",
  title: "デス・ウィッシュ",
  category: "movie",
  releaseDate: "2017",
  country: ["US"],
  notes: "医師のブルースウィリスが、医療知識を活用した脅迫をする",
},
{
  date: "2021/06/24",
  title: "ナイスガイズ！",
  category: "movie",
  releaseDate: "2016",
  country: ["US"],
},
{
  date: "2021/05/29",
  title: "アクアマン",
  category: "movie",
  releaseDate: "2018",
  country: ["US"],
},
{
  date: "2020/12/30",
  title: "レザボア・ドッグス",
  category: "movie",
  releaseDate: "1992",
  country: ["US"],
  notes: "ブシェミがサンジすぎるだろ思ってたらガチの元ネタだった",
},
{
  date: "2020/11/08",
  title: "ミッドナイト・ガイズ",
  category: "movie",
  releaseDate: "2012",
  country: ["US"],
  notes: "いい映画",
},
{
  date: "2020/11/07",
  title: "マシンガン・ツアー リトアニア強奪避航",
  category: "movie",
  releaseDate: "2014",
  country: ["GB", "LT"],
  notes: "なんか妙にいいシーンがある",
},
{
  date: "2020/09/28",
  title: "処刑人",
  category: "movie",
  releaseDate: "1999",
  country: ["US"],
},
{
  date: "2020/09/17",
  title: "ロック、ストック&トゥー・スモーキング・バレルズ",
  category: "movie",
  releaseDate: "1998",
  country: ["GB"],
},
{
  date: "2020/07/23",
  title: "コードネーム U.N.C.L.E.",
  category: "movie",
  releaseDate: "2014",
  country: ["US"],
},
{
  date: "2020/07/22",
  title: "ドライヴ",
  category: "movie",
  releaseDate: "2011",
  country: ["US"],
  notes: "ラスト好き",
},
{
  date: "2020/07/16",
  title: "キングスマン",
  category: "movie",
  releaseDate: "2015",
  country: ["GB", "US"],
},
{
  date: "2020/06/25",
  title: "RED／レッド",
  category: "movie",
  releaseDate: "2010",
  country: ["US"],
},
{
  date: "2020/05/14",
  title: "映画 すみっコぐらし とびだす絵本とひみつのコ",
  category: "movie",
  releaseDate: "2019",
  country: ["JP"],
},
{
  date: "2020/05/14",
  title: "引っ越し大名！",
  category: "movie",
  releaseDate: "2019",
  country: ["JP"],
  notes: "高橋一生が御手杵を振り回す",
},
{
  date: "2020/02/16",
  title: "プロメア",
  category: "movie",
  releaseDate: "2019",
  country: ["JP"],
},
{
  date: "2019/12/27",
  title: "世界侵略:ロサンゼルス決戦",
  category: "movie",
  releaseDate: "2011",
  country: ["US"],
},
{
  date: "2019/12/02",
  title: "LUCY／ルーシー",
  category: "movie",
  releaseDate: "2014",
  country: ["FR"],
},
{
  date: "2019/09/23",
  title: "アベンジャーズ／エンドゲーム",
  category: "movie",
  releaseDate: "2019",
  country: ["US"],
},
{
  date: "2019/08/06",
  title: "ショーン・オブ・ザ・デッド",
  category: "movie",
  releaseDate: "2004",
  country: ["GB"],
  notes: "パブのシーンとラストが好き",
},
{
  date: "2019/07/13",
  title: "映画 刀剣乱舞-継承-",
  category: "movie",
  releaseDate: "2019",
  country: ["JP"],
},
{
  date: "2019/07/03",
  title: "コマンドー",
  category: "movie",
  releaseDate: "1985",
  country: ["US"],
  notes: "ロケランを逆さまに撃つシーンがある",
},
{
  date: "2019/07/02",
  title: "チャーリー・モルデカイ 華麗なる名画の秘密",
  category: "movie",
  releaseDate: "2015",
  country: ["US"],
},
{
  date: "2019/07/01",
  title: "フルメタル・ジャケット",
  category: "movie",
  releaseDate: "1987",
  country: ["GB", "US"],
  notes: "バカヴァッドギーター",
},
{
  date: "2019/06/29",
  title: "ファーゴ",
  category: "movie",
  releaseDate: "1996",
  country: ["US"],
  notes: "ウッドチッパーが活躍する映画",
},
{
  date: "2019/06/28",
  title: "ハードコア",
  category: "movie",
  releaseDate: "2015",
  country: ["RU", "US"],
  notes: "大好き",
  favorite: true,
},
{
  date: "2019/05/18",
  title: "ヒート",
  category: "movie",
  releaseDate: "1995",
  country: ["US"],
},
{
  date: "2019/05/05",
  title: "メメント",
  category: "movie",
  releaseDate: "2000",
  country: ["US"],
  notes: "目を閉じても世界は消えない",
},
{
  date: "2019/05/04",
  title: "ロシアン・ブレイカーズ",
  category: "movie",
  releaseDate: "2013",
  country: ["RU"],
  notes: "妙に構図が上手いロシアの現代版桃太郎",
  favorite: true,
},
{
  date: "2019/04/07",
  title: "名探偵コナン ゼロの執行人",
  category: "movie",
  releaseDate: "2018",
  country: ["JP"],
},
{
  date: "2019/04/06",
  title: "ブレードランナー ファイナル・カット",
  category: "movie",
  releaseDate: "2007",
  country: ["US"],
},
{
  date: "2019/03/02",
  title: "ミッション：インポッシブル／ゴースト・プロトコル",
  category: "movie",
  releaseDate: "2011",
  country: ["US"],
},
{
  date: "2019/02/21",
  title: "ミッション：インポッシブル／フォールアウト",
  category: "movie",
  releaseDate: "2018",
  country: ["US"],
},
{
  date: "2019/02/20",
  title: "グランド・イリュージョン 見破られたトリック",
  category: "movie",
  releaseDate: "2016",
  country: ["US"],
  notes: "雨のシーン本当にかっこいい",
},
{
  date: "2020/02/20",
  title: "グランド・イリュージョン",
  category: "movie",
  releaseDate: "2013",
  country: ["US", "FR"],
},
{
  date: "2019/01/28",
  title: "シャイニング",
  category: "movie",
  releaseDate: "1980",
  country: ["GB"],
},
{
  date: "2019/01/12",
  title: "キング・オブ・エジプト",
  category: "movie",
  releaseDate: "2016",
  country: ["US"],
},
{
  date: "2019/01/11",
  title: "ノッキン・オン・ヘブンズ・ドア",
  category: "movie",
  releaseDate: "1997",
  country: ["DE"],
  notes: "大好き",
  favorite: true,
},
{
  date: "2019/01/05",
  title: "グレートウォール",
  category: "movie",
  releaseDate: "2016",
  country: ["US"],
},
{
  date: "2019/01/05",
  title: "ジオストーム",
  category: "movie",
  releaseDate: "2017",
  country: ["US"],
},
{
  date: "2019/01/05",
  title: "レジェンド 狂気の美学",
  category: "movie",
  releaseDate: "2015",
  country: ["GB"],
  notes: "ラストが大好き",
},
{
  date: "2019/01/03",
  title: "ファイティング・ダディ 怒りの除雪車",
  category: "movie",
  releaseDate: "2014",
  country: ["NO", "SE", "DK"],
  notes: "なんか妙にいいシーンがたくさんある",
},
{
  date: "2019/01/03",
  title: "トロピック・サンダー／史上最低の作戦",
  category: "movie",
  releaseDate: "2008",
  country: ["US"],
},
{
  date: "2018/12/25",
  title: "怪盗グルーのミニオン危機一発",
  category: "movie",
  releaseDate: "2013",
  country: ["US"],
},
{
  date: "2018/12/25",
  title: "ミニオンズ",
  category: "movie",
  releaseDate: "2015",
  country: ["US"],
},
{
  date: "2018/12/24",
  title: "ミッション：インポッシブル／ローグ・ネイション",
  category: "movie",
  releaseDate: "2015",
  country: ["US"],
  notes: "オペラのシーン大好き",
},
{
  date: "2018/11/24",
  title: "クローズEXPLODE（エクスプロ―ド）",
  category: "movie",
  releaseDate: "2014",
  country: ["JP"],
},
{
  date: "2018/11/05",
  title: "リメンバー・ミー",
  category: "movie",
  releaseDate: "2017",
  country: ["US"],
},
{
  date: "2018/10/10",
  title: "容疑者Xの献身",
  category: "movie",
  releaseDate: "2008",
  country: ["JP"],
},
{
  date: "2018/10/08",
  title: "ミスト",
  category: "movie",
  releaseDate: "2007",
  country: ["US"],
},
{
  date: "2018/10/08",
  title: "時計じかけのオレンジ",
  category: "movie",
  releaseDate: "1971",
  country: ["GB"],
},
{
  date: "2018/10/07",
  title: "グッドフェローズ",
  category: "movie",
  releaseDate: "1990",
  country: ["US"],
},
{
  date: "2018/10/04",
  title: "HiGH&LOW THE MOVIE3 / FINAL MISSION",
  category: "movie",
  releaseDate: "2017",
  country: ["JP"],
},
{
  date: "2018/10/04",
  title: "銀魂",
  category: "movie",
  releaseDate: "2017",
  country: ["JP"],
},
{
  date: "2018/10/04",
  title: "HiGH&LOW THE MOVIE2 / END OF SKY",
  category: "movie",
  releaseDate: "2017",
  country: ["JP"],
},
{
  date: "2018/10/04",
  title: "HiGH&LOW THE MOVIE",
  category: "movie",
  releaseDate: "2016",
  country: ["JP"],
},
{
  date: "2018/09/06",
  title: "銀魂２　掟は破るためにこそある",
  category: "movie",
  releaseDate: "2018",
  country: ["JP"],
},
{
  date: "2018/07/11",
  title: "タッカーとデイル 史上最悪にツイてないヤツら",
  category: "movie",
  releaseDate: "2010",
  country: ["CA"],
  notes: "ウッドチッパーが活躍する映画",
},
{
  date: "2018/06/08",
  title: "ギャングスター・ナンバー1",
  category: "movie",
  releaseDate: "2000",
  country: ["GB", "DE"],
  notes: "ポールベタニーとデヴィッドシューリスが激アツ",
},
{
  date: "2018/06/03",
  title: "レオン 完全版",
  category: "movie",
  releaseDate: "1994",
  country: ["FR", "US"],
  notes: "Bingo!",
},
{
  date: "2018/06/03",
  title: "バーフバリ 伝説誕生",
  category: "movie",
  releaseDate: "2015",
  country: ["IN"],
},
{
  date: "2018/06/01",
  title: "ナインスゲート",
  category: "movie",
  releaseDate: "1999",
  country: ["FR", "ES"],
},
{
  date: "2018/06/01",
  title: "セブン",
  category: "movie",
  releaseDate: "1995",
  country: ["US"],
},
{
  date: "2018/06/01",
  title: "ファイト・クラブ",
  category: "movie",
  releaseDate: "1999",
  country: ["US"],
},
{
  date: "2018/06/01",
  title: "真夏の方程式",
  category: "movie",
  releaseDate: "2013",
  country: ["JP"],
},

]

function parseRecordDate(value?: string | Date) {
  if (value instanceof Date) return value
  if (typeof value !== "string" || !value.trim()) return undefined

  const normalized = value.trim().replaceAll("/", "-")
  const date = new Date(`${normalized}T00:00:00`)
  return Number.isNaN(date.getTime()) ? undefined : date
}

function resolveRecordEntry(entry: RecordEntry): ResolvedRecordEntry {
  return {
    date: parseRecordDate(entry.date),
    title: entry.title,
    category: entry.category ?? "other",
    url: entry.url ?? "",
    creator: entry.creator ?? "",
    releaseDate: entry.releaseDate ?? "",
    country: Array.isArray(entry.country)
      ? entry.country
      : entry.country
        ? [entry.country]
        : [],
    notes: entry.notes ?? "",
    favorite: entry.favorite === true,
  }
}

const compareRecordDates = (left?: Date, right?: Date) => {
  if (!left && !right) return 0
  if (!left) return 1
  if (!right) return -1

  return right.getTime() - left.getTime()
}

export function getRecordEntries() {
  return [...recordEntries]
    .map(resolveRecordEntry)
    .sort((a, b) => compareRecordDates(a.date, b.date))
}