export type RecordCategory = "book" | "movie" | "game" | "other"

export type RecordEntry = {
  date?: string | Date
  title: string
  category?: RecordCategory
  url?: string
  creator?: string
  releaseDate?: string
  country?: string | string[]
  notes?: string
  favorite?: true
}

export type ResolvedRecordEntry = {
  date?: Date
  title: string
  category: RecordCategory
  url: string
  creator: string
  releaseDate: string
  country: string []
  notes: string
  favorite: boolean
}

const recordEntries: RecordEntry[] = [

{
  date: "2022/12/09",
  title: "What Remains of Edith Finch",
  category: "game",
  creator: "Giant Sparrow",
  releaseDate: "2017",
  country: ["US"],
  notes: "Switch、インディー"
},
{
  date: "2021/06/17",
  title: "The Red Strings Club",
  category: "game",
  creator: "Deconstructeam",
  releaseDate: "2018",
  country: ["ES"],
 notes: "Switch、インディー"
},
{
  date: "2020/07/12",
  title: "Stories Untold",
  category: "game",
  creator: "No Code",
  releaseDate: "2017",
  country: ["GB"],
 notes: "Switch、インディー"
},
{
  date: "2020/05/26",
  title: "Hell's High Harmonizers",
  creator: "Dear Done Dead",
  category: "game",
  releaseDate: "2020",
  country: ["JP"],
  notes: "Switch、インディー"
},
{
  date: "2020/12/14",
  title: "Transistor",
  creator: "Supergiant Games",
  category: "game",
  releaseDate: "2014",
  country: ["US"],
  notes: "Switch、インディー"
},
{
  date: "2020/11/24",
  title: "Baba Is You",
  creator: "hempuli",
  category: "game",
  releaseDate: "2019",
  country: ["FI"],
  notes: "Switch、インディー",
},
{
  date: "2021/06/03",
  title: "Sludge Life",
  creator: "Terri Vellmann",
  category: "game",
  releaseDate: "2020",
  country: ["BR"],
  notes: "Switch、インディー",
  favorite: true,
},
{
  date: "2022/05/08",
  title: "OlliOlli World",
  creator: "Roll7",
  category: "game",
  releaseDate: "2022",
  country: ["GB"],
  notes: "Switch、インディー",
},
{
  date: "2021/06/06",
  title: "Umurangi Generation",
  creator: "ORIGAME DIGITAL",
  category: "game",
  releaseDate: "2020",
  country: ["AU"],
  notes: "Switch、インディー",
  favorite: true,
},
{
  date: "2020/11/03",
  title: "My Friend Pedro",
  creator: "DeadToast Entertainment",
  category: "game",
  releaseDate: "2019",
  country: ["SE"],
  notes: "Switch、インディー",
  favorite: true,
},
{
  date: "2020/07/13",
  title: "Ruiner",
  creator: "Reikon Games",
  category: "game",
  releaseDate: "2017",
  country: ["PL"],
  notes: "Switch、インディー",
},
{
  date: "2021/03/02",
  title: "Stardew Valley",
  creator: "ConcernedApe",
  category: "game",
  releaseDate: "2016",
  country: ["US"],
  notes: "Switch、インディー",
},
{
  date: "2020/10/15",
  title: "Katana ZERO",
  creator: "Askiisoft",
  category: "game",
  releaseDate: "2019",
  country: ["US"],
  notes: "Switch、インディー",
},
{
  date: "2020/12/27",
  title: "UNDERTALE",
  creator: "tobyfox",
  category: "game",
  releaseDate: "2015",
  country: ["US"],
  notes: "Switch、インディー",
},
{
  date: "2021/01/01",
  title: "Neon Abyss",
  creator: "Veewo Games",
  category: "game",
  releaseDate: "2020",
  country: ["CN"],
  notes: "Switch、インディー",
},
{
  date: "2020/09/03",
  title: "Hyper Light Drifter: Special Edition",
  creator: "Heart Machine",
  category: "game",
  releaseDate: "2018",
  country: ["US"],
  notes: "Switch、インディー",
},
{
  date: "2022/02/11",
  title: "HADES",
  creator: "Supergiant Games",
  category: "game",
  releaseDate: "2020",
  country: ["US"],
  notes: "Switch、インディー",
},
{
  date: "2020/08/27",
  title: "Hotline Miami",
  creator: "Dennaton Games",
  category: "game",
  releaseDate: "2012",
  country: ["SE"],
  notes: "PSVITA、インディー",
  favorite: true,
},
{
  date: "2020/08/30",
  title: "Hotline Miami 2: Wrong Number",
  creator: "Dennaton Games",
  category: "game",
  releaseDate: "2015",
  country: ["SE"],
  notes: "PSVITA、インディー",
  favorite: true,
},
{
  date: "2020/04/15",
  title: "あつまれ どうぶつの森",
  creator: "任天堂",
  category: "game",
  releaseDate: "2020",
  country: ["JP"],
  notes: "Switch",
},
{
  date: "2026/06/10",
  title: "Skate Story",
  creator: "Sam Eng",
  category: "game",
  releaseDate: "2025",
  country: ["US"],
  notes: "PS5、インディー",
  favorite: true,
},
{
  date: "2023/04/04",
  title: "Far Cry 3",
  creator: "Ubisoft Montreal",
  category: "game",
  releaseDate: "2012",
  country: ["CA"],
  notes: "PS5",
  favorite: true,
},
{
  date: "2023/02/08",
  title: "Far Cry 4",
  creator: "Ubisoft Montreal",
  category: "game",
  releaseDate: "2014",
  country: ["CA"],
  notes: "PS5",
  favorite: true,
},
{
  date: "2023/03/18",
  title: "Far Cry 6",
  creator: "Ubisoft Toronto",
  category: "game",
  releaseDate: "2021",
  country: ["CA"],
  notes: "PS5",
  favorite: true,
},
{
  date: "2023/03/02",
  title: "Far Cry 5",
  creator: "Ubisoft Montreal",
  category: "game",
  releaseDate: "2016",
  country: ["CA"],
  notes: "PS5",
  favorite: true,
},
{
  date: "2023/06/13",
  title: "Boyfriend Dungeon",
  creator: "Kitfox Games",
  category: "game",
  releaseDate: "2021",
  country: ["CA"],
  notes: "PS5、インディー",
},
{
  date: "2024/11/14",
  title: "龍が如く0　誓いの場所",
  creator: "セガ",
  category: "game",
  releaseDate: "2016",
  country: ["JP"],
  notes: "PS5",
},
{
  date: "2023/09/17",
  title: "Titanfall 2",
  creator: "Respawn Entertainment",
  category: "game",
  releaseDate: "2016",
  country: ["US"],
  notes: "PS5",
},
{
  date: "2023/12/11",
  title: "Firewatch",
  creator: "Campo Santo",
  category: "game",
  releaseDate: "2016",
  country: ["US"],
  notes: "PS5、インディー",
},
{
  date: "2024/04/02",
  title: "Rise of the Ronin",
  creator: "Team NINJA",
  category: "game",
  releaseDate: "2024",
  country: ["JP"],
  notes: "PS5",
},
{
  date: "2023/04/16",
  title: "Cyberpunk 2077",
  creator: "CD Projekt RED",
  category: "game",
  releaseDate: "2020",
  country: ["PL"],
  notes: "PS5",
  favorite: true,
},{
  date: "2023/09/26",
  title: "Cyberpunk 2077: Phantom Liberty",
  creator: "CD Projekt RED",
  category: "game",
  releaseDate: "2023",
  country: ["PL"],
  notes: "PS5",
  favorite: true,
},
{
  date: "2024/01/11",
  title: "Baldur's Gate 3",
  creator: "Larian Studios",
  category: "game",
  releaseDate: "2023",
  country: ["BE"],
  notes: "Steam",
},
{
  date: "2024/08/07",
  title: "Call of Duty®: Black Ops Cold War",
  creator: "Treyarch",
  category: "game",
  releaseDate: "2020",
  country: ["US"],
  notes: "Steam",
  favorite: true,
},
{
  date: "2025/01/12",
  title: "Call of Duty®: Black Ops 6",
  creator: "Treyarch",
  category: "game",
  releaseDate: "2024",
  country: ["US"],
  notes: "Epic Store",
},
{
  date: "2025/05/16",
  title: "Spirit City: Lofi Sessions",
  creator: "Mooncube Games",
  category: "game",
  releaseDate: "2024",
  country: ["CA"],
  notes: "Steam、インディー",
},
{
  date: "2025/04/11",
  title: "スルタンのゲーム",
  creator: "Double Cross",
  category: "game",
  releaseDate: "2025",
  country: ["CN"],
  notes: "Steam、インディー",
  favorite: true,
},
{
  date: "2026/04/26",
  title: "No, I'm not a Human",
  creator: "Trioskaz",
  category: "game",
  releaseDate: "2025",
  country: ["RU"],
  notes: "Steam、インディー",
},
{
  date: "2024/09/27",
  title: "Mouthwashing",
  creator: "Wrong Organ",
  category: "game",
  releaseDate: "2024",
  country: ["SE"],
  notes: "Steam、インディー",
  favorite: true,
},
{
  date: "2023/08/27",
  title: "Papers, Please",
  creator: "Lucas Pope",
  category: "game",
  releaseDate: "2013",
  country: ["US"],
  notes: "Steam、インディー",
},
{
  date: "2023/07/22",
  title: "Sludge Life 2",
  creator: "Terri Vellmann",
  category: "game",
  releaseDate: "2023",
  country: ["BR"],
  notes: "Steam、インディー",
  favorite: true,
},
{
  date: "2023/08/17",
  title: "The Cosmic Wheel Sisterhood",
  creator: "Deconstructeam",
  category: "game",
  releaseDate: "2023",
  country: ["ES"],
  notes: "Steam、インディー",
},
{
  date: "2024/12/06",
  title: "文字化化：Homicipher",
  creator: "Yatsunagi",
  category: "game",
  releaseDate: "2024",
  country: ["JP"],
  notes: "Steam、インディー",
},
{
  date: "2024/05/12",
  title: "Sticky Business",
  creator: "Spellgarden Games",
  category: "game",
  releaseDate: "2023",
  country: ["DE"],
  notes: "Steam、インディー",
},
{
  date: "2024/05/10",
  title: "狂気より愛をこめて",
  creator: "jamsanpoid",
  category: "game",
  releaseDate: "2023",
  country: ["JP"],
  notes: "Steam、インディー",
},
{
  date: "2026/01/01",
  title: "Öoo",
  creator: "NamaTakahashi",
  category: "game",
  releaseDate: "2025",
  country: ["JP"],
  notes: "Steam、インディー",
},
{
  date: "2024/05/17",
  title: "Buckshot Roulette",
  creator: "Mike Klubnika",
  category: "game",
  releaseDate: "2023",
  country: ["EE"],
  notes: "Steam、インディー",
},
{
  date: "2025/02/19",
  title: "PANELKA",
  creator: "MonsterAttack",
  category: "game",
  releaseDate: "2025",
  country: ["RU"],
  notes: "Steam、インディー",
},
{
  date: "2024/03/23",
  title: "Trombone Champ",
  creator: "Holy Wow Studios",
  category: "game",
  releaseDate: "2022",
  country: ["US"],
  notes: "Steam、インディー",
},
{
  date: "2024/08/03",
  title: "Malware",
  creator: "Odd Games",
  category: "game",
  releaseDate: "2024",
  country: ["??"],
  notes: "Steam、インディー",
},
{
  date: "2024/11/10",
  title: "Critters for Sale",
  creator: "Sonoshee",
  category: "game",
  releaseDate: "2021",
  country: ["MA"],
  notes: "Steam、インディー",
},
{
  date: "2024/12/06",
  title: "The Radio Wave Bureau",
  creator: "kiririn51",
  category: "game",
  releaseDate: "2023",
  country: ["ES"],
  notes: "Itch.io、インディー",
},
{
  date: "2024/03/23",
  title: "Off-Peak",
  creator: "Cosmo D Studios",
  category: "game",
  releaseDate: "2015",
  country: ["US"],
  notes: "Steam、インディー",
  favorite: true,
},
{
  date: "2024/08/09",
  title: "The Norwood Suite",
  creator: "Cosmo D Studios",
  category: "game",
  releaseDate: "2017",
  country: ["US"],
  notes: "Steam、インディー",
},
{
  date: "2023/07/26",
  title: "The Complex: Found Footage",
  creator: "pgWave.",
  category: "game",
  releaseDate: "2022",
  country: ["IS"],
  notes: "Steam、インディー",
},
{
  date: "2025/05/21",
  title: "gogh: Focus with Your Avatar",
  creator: "ambr",
  category: "game",
  releaseDate: "2025",
  country: ["JP"],
  notes: "Steam、インディー",
  favorite: true,
},
{
  date: "2023/08/27",
  title: "Milk outside a bag of milk outside a bag of milk",
  creator: "Nikita Kryukov",
  category: "game",
  releaseDate: "2021",
  country: ["RU"],
  notes: "Steam、インディー",
},
{
  date: "2026/02/21",
  title: "Neyasnoe",
  creator: "sad3d",
  category: "game",
  releaseDate: "2023",
  country: ["RU"],
  notes: "Steam、インディー",
},
{
  date: "2025/05/29",
  title: "Indecision.",
  creator: "Bilge Kaan",
  category: "game",
  releaseDate: "2018",
  country: ["??"],
  notes: "Steam、インディー",
},
{
  date: "2023/08/27",
  title: "Milk inside a bag of milk inside a bag of milk",
  creator: "Nikita Kryukov",
  category: "game",
  releaseDate: "2020",
  country: ["RU"],
  notes: "Steam、インディー",
},
{
  date: "2023/08/31",
  title: "Perfect Vermin",
  creator: "ItsTheTalia",
  category: "game",
  releaseDate: "2020",
  country: ["US"],
  notes: "Steam、インディー",
},
{
  date: "",
  title: "ポケットモンスター　ダイヤモンド",
  creator: "ゲームフリーク",
  category: "game",
  releaseDate: "2006",
  country: ["JP"],
  notes: "DS",
},
{
  date: "",
  title: "ポケットモンスター　プラチナ",
  creator: "ゲームフリーク",
  category: "game",
  releaseDate: "2008",
  country: ["JP"],
  notes: "DS",
  favorite: true,
},
{
  date: "",
  title: "ポケットモンスター　ソウルシルバー",
  creator: "ゲームフリーク",
  category: "game",
  releaseDate: "2009",
  country: ["JP"],
  notes: "DS",
},
{
  date: "",
  title: "ポケットモンスター　ブラック",
  creator: "ゲームフリーク",
  category: "game",
  releaseDate: "2010",
  country: ["JP"],
  notes: "DS",
},
{
  date: "",
  title: "ポケットモンスター　ブラック2",
  creator: "ゲームフリーク",
  category: "game",
  releaseDate: "2012",
  country: ["JP"],
  notes: "DS",
},
{
  date: "2017/05/05",
  title: "ポケットモンスター　X",
  creator: "ゲームフリーク",
  category: "game",
  releaseDate: "2013",
  country: ["JP"],
  notes: "3DS",
},
{
  date: "",
  title: "ポケットモンスター　アルファサファイア",
  creator: "ゲームフリーク",
  category: "game",
  releaseDate: "2014",
  country: ["JP"],
  notes: "3DS",
},
{
  date: "",
  title: "ポケットモンスター　サン",
  creator: "ゲームフリーク",
  category: "game",
  releaseDate: "2016",
  country: ["JP"],
  notes: "3DS",
  favorite: true,
},
{
  date: "",
  title: "ポケットモンスター　ムーン",
  creator: "ゲームフリーク",
  category: "game",
  releaseDate: "2016",
  country: ["JP"],
  notes: "3DS",
  favorite: true,
},
{
  date: "",
  title: "ポケットモンスター　ウルトラサン",
  creator: "ゲームフリーク",
  category: "game",
  releaseDate: "2017",
  country: ["JP"],
  notes: "3DS",
},
{
  date: "",
  title: "ポケットモンスター　ウルトラムーン",
  creator: "ゲームフリーク",
  category: "game",
  releaseDate: "2017",
  country: ["JP"],
  notes: "3DS",
},
{
  date: "2020/01/14",
  title: "ポケットモンスター　シールド",
  creator: "ゲームフリーク",
  category: "game",
  releaseDate: "2019",
  country: ["JP"],
  notes: "Switch",
},{
  date: "2020/06/17",
  title: "ポケットモンスター　シールド　鎧の孤島",
  creator: "ゲームフリーク",
  category: "game",
  releaseDate: "2020",
  country: ["JP"],
  notes: "Switch",
},{
  date: "2020/10/23",
  title: "ポケットモンスター　シールド 冠の雪原",
  creator: "ゲームフリーク",
  category: "game",
  releaseDate: "2020",
  country: ["JP"],
  notes: "Switch",
},
{
  date: "2022/01/28",
  title: "Pokémon LEGENDS アルセウス",
  creator: "ゲームフリーク",
  category: "game",
  releaseDate: "2022",
  country: ["JP"],
  notes: "Switch",
},
{
  date: "2022/12/10",
  title: "ポケットモンスター　バイオレット",
  creator: "ゲームフリーク",
  category: "game",
  releaseDate: "2022",
  country: ["JP"],
  notes: "Switch",
  favorite: true,
},{
  date: "2023/09/13",
  title: "ポケットモンスター　バイオレット　碧の仮面",
  creator: "ゲームフリーク",
  category: "game",
  releaseDate: "2023",
  country: ["JP"],
  notes: "Switch",
},{
  date: "2023/12/14",
  title: "ポケットモンスター　バイオレット　藍の円盤",
  creator: "ゲームフリーク",
  category: "game",
  releaseDate: "2023",
  country: ["JP"],
  notes: "Switch",
},
{
  date: "2025/10/24",
  title: "Pokémon LEGENDS Z-A",
  creator: "ゲームフリーク",
  category: "game",
  releaseDate: "2025",
  country: ["JP"],
  notes: "Switch2",
},{
  date: "2025/12/10",
  title: "Pokémon LEGENDS Z-A M次元ラッシュ",
  creator: "ゲームフリーク",
  category: "game",
  releaseDate: "2025",
  country: ["JP"],
  notes: "Switch2",
},
{
  date: "2017/04/10",
  title: "モンスターハンター3G",
  creator: "カプコン",
  category: "game",
  releaseDate: "2011",
  country: ["JP"],
  notes: "3DS",
  favorite: true,
},
{
  date: "2017/03/29",
  title: "モンスターハンタークロス",
  creator: "カプコン",
  category: "game",
  releaseDate: "2015",
  country: ["JP"],
  notes: "3DS",
},
{
  date: "2019/02/15",
  title: "モンスターハンターダブルクロス",
  creator: "カプコン",
  category: "game",
  releaseDate: "2017",
  country: ["JP"],
  notes: "3DS",
},
{
  date: "2021/03/26",
  title: "モンスターハンターライズ",
  creator: "カプコン",
  category: "game",
  releaseDate: "2021",
  country: ["JP"],
  notes: "Switch、PS5",
  favorite: true,
},
{
  date: "2022/06/30",
  title: "モンスターハンターライズ：サンブレイク",
  creator: "カプコン",
  category: "game",
  releaseDate: "2022",
  country: ["JP"],
  notes: "Switch、PS5",
  favorite: true,
},
{
  date: "2025/03/03",
  title: "モンスターハンターワイルズ",
  creator: "カプコン",
  category: "game",
  releaseDate: "2025",
  country: ["JP"],
  notes: "PS5",
},
{
  date: "",
  title: "おいでよ どうぶつの森",
  creator: "任天堂",
  category: "game",
  releaseDate: "2005",
  country: ["JP"],
  notes: "DS",
},
{
  date: "",
  title: "とんがりボウシと魔法の365にち",
  creator: "KONAMI",
  category: "game",
  releaseDate: "2008",
  country: ["JP"],
  notes: "DS",
},

]

function parseRecordDate(value?: string | Date) {
  if (value instanceof Date) return value
  if (typeof value !== "string" || !value.trim()) return undefined

  const normalized = value.trim().replaceAll("/", "-")
  const date = new Date(`${normalized}T00:00:00`)
  return Number.isNaN(date.getTime()) ? undefined : date
}

function resolveRecordEntry(entry: RecordEntry): ResolvedRecordEntry {
  return {
    date: parseRecordDate(entry.date),
    title: entry.title,
    category: entry.category ?? "other",
    url: entry.url ?? "",
    creator: entry.creator ?? "",
    releaseDate: entry.releaseDate ?? "",
    country: Array.isArray(entry.country)
      ? entry.country
      : entry.country
        ? [entry.country]
        : [],
    notes: entry.notes ?? "",
    favorite: entry.favorite === true,
  }
}

const compareRecordDates = (left?: Date, right?: Date) => {
  if (!left && !right) return 0
  if (!left) return 1
  if (!right) return -1

  return right.getTime() - left.getTime()
}

export function getRecordEntries() {
  return [...recordEntries]
    .map(resolveRecordEntry)
    .sort((a, b) => compareRecordDates(a.date, b.date))
}
